#.travis.yml

language: node_js
node_js:
  - "10"
dist: trusty
sudo: false

branches:
  only:
    - master
    - /^greenkeeper/.*$/

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - npm run test:ci
  - ng build --prod --base-href https://dlevkov.github.io/timet-test-prj/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $git_token
  local_dir: dist/denis-test-prj-timer

notifications:
  email:
    on_failure: change
    on_success: change
